<?php

namespace SulimanBenhalim\Prose\Support;

class VerbInflector
{
    private array $irregularVerbs = [
        // Authentication & User Management
        'login' => 'logged in',
        'logout' => 'logged out',
        'signup' => 'signed up',
        'signin' => 'signed in',
        'signout' => 'signed out',
        'register' => 'registered',
        'authenticate' => 'authenticated',
        'authorize' => 'authorized',
        'verify' => 'verified',
        'validate' => 'validated',
        'confirm' => 'confirmed',
        'activate' => 'activated',
        'deactivate' => 'deactivated',
        'suspend' => 'suspended',
        'ban' => 'banned',
        'unban' => 'unbanned',
        'block' => 'blocked',
        'unblock' => 'unblocked',
        'reset' => 'reset',
        'change' => 'changed',
        'update' => 'updated',
        'modify' => 'modified',

        // CRUD Operations
        'create' => 'created',
        'read' => 'read',
        'write' => 'wrote',
        'edit' => 'edited',
        'delete' => 'deleted',
        'remove' => 'removed',
        'insert' => 'inserted',
        'select' => 'selected',
        'find' => 'found',
        'search' => 'searched',
        'filter' => 'filtered',
        'sort' => 'sorted',
        'order' => 'ordered',
        'group' => 'grouped',
        'join' => 'joined',
        'merge' => 'merged',
        'split' => 'split',
        'combine' => 'combined',
        'aggregate' => 'aggregated',
        'count' => 'counted',
        'sum' => 'summed',
        'average' => 'averaged',
        'calculate' => 'calculated',
        'compute' => 'computed',

        // E-commerce & Shopping
        'purchase' => 'purchased',
        'buy' => 'bought',
        'sell' => 'sold',
        'pay' => 'paid',
        'charge' => 'charged',
        'refund' => 'refunded',
        'checkout' => 'checked out',
        'cart' => 'added to cart',
        'wishlist' => 'wishlisted',
        'favorite' => 'favorited',
        'like' => 'liked',
        'unlike' => 'unliked',
        'review' => 'reviewed',
        'rate' => 'rated',
        'recommend' => 'recommended',
        'compare' => 'compared',
        'ship' => 'shipped',
        'deliver' => 'delivered',
        'return' => 'returned',
        'exchange' => 'exchanged',
        'cancel' => 'cancelled',
        'void' => 'voided',
        'process' => 'processed',
        'fulfill' => 'fulfilled',
        'track' => 'tracked',
        'notify' => 'notified',

        // Content Management
        'publish' => 'published',
        'unpublish' => 'unpublished',
        'draft' => 'drafted',
        'schedule' => 'scheduled',
        'approve' => 'approved',
        'reject' => 'rejected',
        'moderate' => 'moderated',
        'flag' => 'flagged',
        'report' => 'reported',
        'hide' => 'hid',
        'show' => 'showed',
        'display' => 'displayed',
        'render' => 'rendered',
        'generate' => 'generated',
        'compile' => 'compiled',
        'build' => 'built',
        'deploy' => 'deployed',
        'release' => 'released',
        'launch' => 'launched',
        'migrate' => 'migrated',
        'seed' => 'seeded',
        'backup' => 'backed up',
        'restore' => 'restored',
        'sync' => 'synced',
        'import' => 'imported',
        'export' => 'exported',
        'upload' => 'uploaded',
        'download' => 'downloaded',

        // Communication & Social
        'message' => 'messaged',
        'email' => 'emailed',
        'mail' => 'mailed',
        'send' => 'sent',
        'receive' => 'received',
        'reply' => 'replied',
        'forward' => 'forwarded',
        'share' => 'shared',
        'post' => 'posted',
        'comment' => 'commented',
        'mention' => 'mentioned',
        'tag' => 'tagged',
        'untag' => 'untagged',
        'follow' => 'followed',
        'unfollow' => 'unfollowed',
        'subscribe' => 'subscribed',
        'unsubscribe' => 'unsubscribed',
        'invite' => 'invited',
        'accept' => 'accepted',
        'decline' => 'declined',
        'ignore' => 'ignored',
        'mute' => 'muted',
        'unmute' => 'unmuted',
        'chat' => 'chatted',
        'call' => 'called',
        'video' => 'video called',

        // File & Media Management
        'save' => 'saved',
        'load' => 'loaded',
        'open' => 'opened',
        'close' => 'closed',
        'copy' => 'copied',
        'move' => 'moved',
        'rename' => 'renamed',
        'compress' => 'compressed',
        'decompress' => 'decompressed',
        'zip' => 'zipped',
        'unzip' => 'unzipped',
        'archive' => 'archived',
        'unarchive' => 'unarchived',
        'resize' => 'resized',
        'crop' => 'cropped',
        'rotate' => 'rotated',
        'flip' => 'flipped',
        'convert' => 'converted',
        'encode' => 'encoded',
        'decode' => 'decoded',
        'encrypt' => 'encrypted',
        'decrypt' => 'decrypted',
        'hash' => 'hashed',
        'sign' => 'signed',

        // System & Administrative
        'install' => 'installed',
        'uninstall' => 'uninstalled',
        'configure' => 'configured',
        'setup' => 'set up',
        'initialize' => 'initialized',
        'start' => 'started',
        'stop' => 'stopped',
        'pause' => 'paused',
        'resume' => 'resumed',
        'restart' => 'restarted',
        'refresh' => 'refreshed',
        'reload' => 'reloaded',
        'clear' => 'cleared',
        'flush' => 'flushed',
        'purge' => 'purged',
        'clean' => 'cleaned',
        'maintain' => 'maintained',
        'optimize' => 'optimized',
        'debug' => 'debugged',
        'test' => 'tested',
        'monitor' => 'monitored',
        'log' => 'logged',
        'audit' => 'audited',
        'trace' => 'traced',
        'profile' => 'profiled',
        'benchmark' => 'benchmarked',

        // Workflow & Status
        'queue' => 'queued',
        'delay' => 'delayed',
        'retry' => 'retried',
        'fail' => 'failed',
        'succeed' => 'succeeded',
        'complete' => 'completed',
        'finish' => 'finished',
        'abort' => 'aborted',
        'timeout' => 'timed out',
        'expire' => 'expired',
        'renew' => 'renewed',
        'extend' => 'extended',
        'shorten' => 'shortened',
        'enable' => 'enabled',
        'disable' => 'disabled',
        'toggle' => 'toggled',
        'switch' => 'switched',
        'transition' => 'transitioned',
        'transform' => 'transformed',
        'upgrade' => 'upgraded',
        'downgrade' => 'downgraded',

        // Analytics & Reporting
        'visit' => 'visited',
        'view' => 'viewed',
        'browse' => 'browsed',
        'navigate' => 'navigated',
        'click' => 'clicked',
        'tap' => 'tapped',
        'swipe' => 'swiped',
        'scroll' => 'scrolled',
        'zoom' => 'zoomed',
        'focus' => 'focused',
        'blur' => 'blurred',
        'hover' => 'hovered',
        'drag' => 'dragged',
        'drop' => 'dropped',
        'deselect' => 'deselected',
        'highlight' => 'highlighted',
        'mark' => 'marked',
        'unmark' => 'unmarked',
        'bookmark' => 'bookmarked',
        'unbookmark' => 'unbookmarked',

        // API & Integration
        'request' => 'requested',
        'respond' => 'responded',
        'callback' => 'called back',
        'webhook' => 'webhooks sent',
        'push' => 'pushed',
        'pull' => 'pulled',
        'fetch' => 'fetched',
        'poll' => 'polled',
        'stream' => 'streamed',
        'broadcast' => 'broadcasted',
        'emit' => 'emitted',
        'listen' => 'listened',
        'trigger' => 'triggered',
        'fire' => 'fired',
        'dispatch' => 'dispatched',
        'handle' => 'handled',
        'execute' => 'executed',
        'run' => 'ran',
        'invoke' => 'invoked',

        // Gaming & Gamification
        'play' => 'played',
        'win' => 'won',
        'lose' => 'lost',
        'score' => 'scored',
        'level' => 'leveled up',
        'unlock' => 'unlocked',
        'achieve' => 'achieved',
        'challenge' => 'challenged',
        'compete' => 'competed',
        'rank' => 'ranked',
        'reward' => 'rewarded',
        'badge' => 'earned badge',
        'point' => 'earned points',

        // Learning & Education
        'learn' => 'learned',
        'study' => 'studied',
        'practice' => 'practiced',
        'exercise' => 'exercised',
        'quiz' => 'took quiz',
        'exam' => 'took exam',
        'grade' => 'graded',
        'pass' => 'passed',
        'graduate' => 'graduated',
        'enroll' => 'enrolled',
        'attend' => 'attended',
        'participate' => 'participated',
        'contribute' => 'contributed',
        'collaborate' => 'collaborated',

        // Health & Fitness
        'workout' => 'worked out',
        'walk' => 'walked',
        'bike' => 'biked',
        'swim' => 'swam',
        'stretch' => 'stretched',
        'meditate' => 'meditated',
        'sleep' => 'slept',
        'wake' => 'woke up',
        'eat' => 'ate',
        'drink' => 'drank',
        'weigh' => 'weighed',
        'measure' => 'measured',

        // Financial & Accounting
        'spend' => 'spent',
        'earn' => 'earned',
        'invest' => 'invested',
        'withdraw' => 'withdrew',
        'deposit' => 'deposited',
        'transfer' => 'transferred',
        'trade' => 'traded',
        'budget' => 'budgeted',
        'forecast' => 'forecasted',
        'reconcile' => 'reconciled',
        'invoice' => 'invoiced',
        'bill' => 'billed',
        'credit' => 'credited',
        'debit' => 'debited',

        // Travel & Location
        'travel' => 'traveled',
        'checkin' => 'checked in',
        'book' => 'booked',
        'reserve' => 'reserved',
        'reschedule' => 'rescheduled',
        'arrive' => 'arrived',
        'depart' => 'departed',
        'board' => 'boarded',
        'land' => 'landed',
        'drive' => 'drove',
        'fly' => 'flew',
        'sail' => 'sailed',
        'locate' => 'located',
        'map' => 'mapped',

        // Regular verb patterns (add -ed)
        'access' => 'accessed',
        'add' => 'added',
        'allow' => 'allowed',
        'appear' => 'appeared',
        'apply' => 'applied',
        'assign' => 'assigned',
        'attach' => 'attached',
        'attempt' => 'attempted',
        'avoid' => 'avoided',
        'belong' => 'belonged',
        'cache' => 'cached',
        'capture' => 'captured',
        'check' => 'checked',
        'claim' => 'claimed',
        'collapse' => 'collapsed',
        'collect' => 'collected',
        'connect' => 'connected',
        'contain' => 'contained',
        'continue' => 'continued',
        'control' => 'controlled',
        'decide' => 'decided',
        'declare' => 'declared',
        'decrease' => 'decreased',
        'depend' => 'depended',
        'describe' => 'described',
        'destroy' => 'destroyed',
        'detect' => 'detected',
        'develop' => 'developed',
        'differ' => 'differed',
        'direct' => 'directed',
        'disappear' => 'disappeared',
        'discover' => 'discovered',
        'discuss' => 'discussed',
        'distribute' => 'distributed',
        'divide' => 'divided',
        'duplicate' => 'duplicated',
        'eliminate' => 'eliminated',
        'empty' => 'emptied',
        'encourage' => 'encouraged',
        'end' => 'ended',
        'engage' => 'engaged',
        'enjoy' => 'enjoyed',
        'enter' => 'entered',
        'establish' => 'established',
        'estimate' => 'estimated',
        'evaluate' => 'evaluated',
        'examine' => 'examined',
        'exceed' => 'exceeded',
        'exclude' => 'excluded',
        'expand' => 'expanded',
        'expect' => 'expected',
        'explain' => 'explained',
        'explore' => 'explored',
        'express' => 'expressed',
        'face' => 'faced',
        'feature' => 'featured',
        'fill' => 'filled',
        'force' => 'forced',
        'form' => 'formed',
        'format' => 'formatted',
        'function' => 'functioned',
        'gather' => 'gathered',
        'grant' => 'granted',
        'guard' => 'guarded',
        'guide' => 'guided',
        'happen' => 'happened',
        'help' => 'helped',
        'identify' => 'identified',
        'imagine' => 'imagined',
        'implement' => 'implemented',
        'improve' => 'improved',
        'include' => 'included',
        'increase' => 'increased',
        'indicate' => 'indicated',
        'influence' => 'influenced',
        'inform' => 'informed',
        'inspect' => 'inspected',
        'integrate' => 'integrated',
        'intend' => 'intended',
        'interact' => 'interacted',
        'interest' => 'interested',
        'interpret' => 'interpreted',
        'introduce' => 'introduced',
        'involve' => 'involved',
        'issue' => 'issued',
        'iterate' => 'iterated',
        'jump' => 'jumped',
        'justify' => 'justified',
        'keep' => 'kept',
        'label' => 'labeled',
        'lead' => 'led',
        'leave' => 'left',
        'limit' => 'limited',
        'link' => 'linked',
        'list' => 'listed',
        'live' => 'lived',
        'lock' => 'locked',
        'loop' => 'looped',
        'manage' => 'managed',
        'match' => 'matched',
        'maximize' => 'maximized',
        'mean' => 'meant',
        'minimize' => 'minimized',
        'miss' => 'missed',
        'mix' => 'mixed',
        'model' => 'modeled',
        'multiply' => 'multiplied',
        'name' => 'named',
        'need' => 'needed',
        'note' => 'noted',
        'notice' => 'noticed',
        'observe' => 'observed',
        'obtain' => 'obtained',
        'occur' => 'occurred',
        'offer' => 'offered',
        'operate' => 'operated',
        'organize' => 'organized',
        'override' => 'overridden',
        'own' => 'owned',
        'pack' => 'packed',
        'parse' => 'parsed',
        'patch' => 'patched',
        'perform' => 'performed',
        'permit' => 'permitted',
        'pick' => 'picked',
        'place' => 'placed',
        'plan' => 'planned',
        'populate' => 'populated',
        'position' => 'positioned',
        'predict' => 'predicted',
        'prefer' => 'preferred',
        'prepare' => 'prepared',
        'present' => 'presented',
        'preserve' => 'preserved',
        'press' => 'pressed',
        'prevent' => 'prevented',
        'print' => 'printed',
        'prioritize' => 'prioritized',
        'proceed' => 'proceeded',
        'produce' => 'produced',
        'program' => 'programmed',
        'progress' => 'progressed',
        'project' => 'projected',
        'promise' => 'promised',
        'promote' => 'promoted',
        'propose' => 'proposed',
        'protect' => 'protected',
        'provide' => 'provided',
        'query' => 'queried',
        'question' => 'questioned',
        'quote' => 'quoted',
        'raise' => 'raised',
        'range' => 'ranged',
        'reach' => 'reached',
        'realize' => 'realized',
        'reason' => 'reasoned',
        'recognize' => 'recognized',
        'record' => 'recorded',
        'recover' => 'recovered',
        'reduce' => 'reduced',
        'refer' => 'referred',
        'reflect' => 'reflected',
        'refuse' => 'refused',
        'regard' => 'regarded',
        'relate' => 'related',
        'remain' => 'remained',
        'remember' => 'remembered',
        'repeat' => 'repeated',
        'replace' => 'replaced',
        'represent' => 'represented',
        'require' => 'required',
        'research' => 'researched',
        'resolve' => 'resolved',
        'restrict' => 'restricted',
        'result' => 'resulted',
        'retrieve' => 'retrieved',
        'reveal' => 'revealed',
        'revise' => 'revised',
        'round' => 'rounded',
        'rule' => 'ruled',
        'satisfy' => 'satisfied',
        'scale' => 'scaled',
        'scan' => 'scanned',
        'scope' => 'scoped',
        'secure' => 'secured',
        'separate' => 'separated',
        'serve' => 'served',
        'session' => 'sessioned',
        'simplify' => 'simplified',
        'simulate' => 'simulated',
        'skip' => 'skipped',
        'solve' => 'solved',
        'source' => 'sourced',
        'specify' => 'specified',
        'state' => 'stated',
        'stay' => 'stayed',
        'step' => 'stepped',
        'store' => 'stored',
        'structure' => 'structured',
        'style' => 'styled',
        'submit' => 'submitted',
        'suggest' => 'suggested',
        'summarize' => 'summarized',
        'supply' => 'supplied',
        'support' => 'supported',
        'suppose' => 'supposed',
        'surface' => 'surfaced',
        'system' => 'systemed',
        'table' => 'tabled',
        'target' => 'targeted',
        'task' => 'tasked',
        'teach' => 'taught',
        'template' => 'templated',
        'tend' => 'tended',
        'terminate' => 'terminated',
        'thank' => 'thanked',
        'theme' => 'themed',
        'think' => 'thought',
        'throw' => 'threw',
        'time' => 'timed',
        'title' => 'titled',
        'tool' => 'tooled',
        'top' => 'topped',
        'total' => 'totaled',
        'touch' => 'touched',
        'train' => 'trained',
        'translate' => 'translated',
        'transmit' => 'transmitted',
        'transport' => 'transported',
        'treat' => 'treated',
        'trim' => 'trimmed',
        'trust' => 'trusted',
        'try' => 'tried',
        'tune' => 'tuned',
        'turn' => 'turned',
        'type' => 'typed',
        'understand' => 'understood',
        'undo' => 'undid',
        'unite' => 'united',
        'unpack' => 'unpacked',
        'use' => 'used',
        'utilize' => 'utilized',
        'value' => 'valued',
        'vary' => 'varied',
        'version' => 'versioned',
        'visualize' => 'visualized',
        'vote' => 'voted',
        'wait' => 'waited',
        'want' => 'wanted',
        'warn' => 'warned',
        'watch' => 'watched',
        'welcome' => 'welcomed',
        'work' => 'worked',
        'zone' => 'zoned',
    ];

    public function toPastTense(string $verb): string
    {
        $verb = strtolower(trim($verb));

        if (isset($this->irregularVerbs[$verb])) {
            return $this->irregularVerbs[$verb];
        }

        // Already a past participle (created, updated, scheduled, ...).
        // Words like "need" or "embed" that genuinely end in -ed belong in
        // the irregular map instead.
        if (strlen($verb) > 3 && str_ends_with($verb, 'ed')) {
            return $verb;
        }

        if (preg_match('/^(.+[bcdfghjklmnpqrstvwxz])y$/', $verb, $matches)) {
            return $matches[1].'ied';
        }

        if (preg_match('/^(.+[bcdfghjklmnpqrstvwxz])[bcdfghjklmnpqrstvwxz]$/', $verb) &&
            ! preg_match('/(ch|sh|th|ph|ck)$/', $verb)) {
            return $verb.substr($verb, -1).'ed';
        }

        if (preg_match('/e$/', $verb)) {
            return $verb.'d';
        }

        return $verb.'ed';
    }

    public function hasMapping(string $verb): bool
    {
        return isset($this->irregularVerbs[strtolower(trim($verb))]);
    }

    public function getAllMappings(): array
    {
        return $this->irregularVerbs;
    }
}
